## Copyright 2022 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

dependencies:
  - name: git
    version: "2"
    download-link-windows: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.gz
    download-link-linux:
    checksums: 
      - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.sign
      - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.xz
source:
  - instanceName: acm-custom-controller
    repo: https://github.com/AgileCloudInstitute/acm-custom-controller.git
    branch: main
    public: true
  - instanceName: acm-system-templates
    repo: https://github.com/AgileCloudInstitute/acm-system-templates.git
    branch: main
    public: true
